// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPQQ2Kmz-GxWQyvuqDMv5L3ZwNvvM5fc',
    appId: '1:895280838640:web:0c7cb9278f296219d48f35',
    messagingSenderId: '895280838640',
    projectId: 'flutter-chat-app-4e92b',
    authDomain: 'flutter-chat-app-4e92b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4e92b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvdooaWBL-lYLXaXhJbn4jmmMaju7H3e8',
    appId: '1:895280838640:android:d0156f0013c1aa5bd48f35',
    messagingSenderId: '895280838640',
    projectId: 'flutter-chat-app-4e92b',
    storageBucket: 'flutter-chat-app-4e92b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMntoxwdV5r0NJI1weiSYsU19wU0kVzLc',
    appId: '1:895280838640:ios:fd66a4fe07ec1fb8d48f35',
    messagingSenderId: '895280838640',
    projectId: 'flutter-chat-app-4e92b',
    storageBucket: 'flutter-chat-app-4e92b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
